server:
  port: 9003
  context-path: /db
spring:
  application:
    name: DatabaseService
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdemo
    username: root
    password: root
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true